// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9fgGtrfWF9-unqxteudC2gl8tyCmGVlU',
    appId: '1:1056485373425:web:ffa714e06b276ab0f10050',
    messagingSenderId: '1056485373425',
    projectId: 'woofs-the-way',
    authDomain: 'woofs-the-way.firebaseapp.com',
    storageBucket: 'woofs-the-way.appspot.com',
    measurementId: 'G-DLFQZ96T4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-xUh_jfoI-WqkShj2LjvhTSZDuzA-gAQ',
    appId: '1:1056485373425:android:9f3da5de9b7ccd9df10050',
    messagingSenderId: '1056485373425',
    projectId: 'woofs-the-way',
    storageBucket: 'woofs-the-way.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8RNz4LXyQFM9jW78EJZxtwpAhoVN5iSI',
    appId: '1:1056485373425:ios:ea88bb9c2a93b57df10050',
    messagingSenderId: '1056485373425',
    projectId: 'woofs-the-way',
    storageBucket: 'woofs-the-way.appspot.com',
    iosClientId: '1056485373425-sipka65hqhn54pgo4deua2p8b2l6o0fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8RNz4LXyQFM9jW78EJZxtwpAhoVN5iSI',
    appId: '1:1056485373425:ios:ea88bb9c2a93b57df10050',
    messagingSenderId: '1056485373425',
    projectId: 'woofs-the-way',
    storageBucket: 'woofs-the-way.appspot.com',
    iosClientId: '1056485373425-sipka65hqhn54pgo4deua2p8b2l6o0fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );
}
